/**
 * LLM-Driven Content Enrichment
 *
 * Uses LLM to intelligently:
 * 1. Generate optimal search queries based on perceived content
 * 2. Synthesize search results into structured data
 * 3. Format responses for users
 */

import OpenAI from "openai";
import {
  searchWithTavily,
  type TavilyResponse,
  isTavilyConfigured,
} from "./tavily-client";
import type { PerceiveOutput } from "@/lib/services/ai/nova/perception";

let openaiInstance: OpenAI | null = null;

function getOpenAI(): OpenAI {
  if (!openaiInstance) {
    const apiKey = process.env.OPENAI_API_KEY;
    if (!apiKey) {
      throw new Error("OPENAI_API_KEY environment variable is required");
    }
    openaiInstance = new OpenAI({ apiKey });
  }
  return openaiInstance;
}

/**
 * Search context generated by LLM
 */
export interface SearchContext {
  query: string;
  searchIntent: string;
  fieldsToExtract: string[];
  shouldSearch: boolean;
}

/**
 * Enriched data structure
 */
export interface EnrichedData {
  title: string;
  description: string;
  keyFacts: Record<string, unknown>;
  tags: string[];
  category: string;
  sourceUrl?: string;
  confidence: number;
}

/**
 * LLM generates optimal search query based on content understanding
 */
export async function generateSearchQuery(
  perception: PerceiveOutput,
): Promise<SearchContext> {
  const openai = getOpenAI();

  console.log(
    `[Enrichment] Generating search query for: ${perception.contentType}`,
  );

  const response = await openai.chat.completions.create({
    model: "gpt-4o-mini",
    max_tokens: 500,
    response_format: { type: "json_object" },
    messages: [
      {
        role: "system",
        content: `You are a search query optimizer. Given content analysis, determine:
1. Whether a web search would be beneficial
2. The best web search query to find useful information
3. What the user likely wants to know about this
4. What specific fields/data would be valuable to extract

Return JSON:
{
  "shouldSearch": true/false,
  "query": "optimized search query string",
  "searchIntent": "what we're trying to find",
  "fieldsToExtract": ["list", "of", "useful", "data", "points"]
}

GUIDELINES:
- For restaurants: search for address, prices, reviews, cuisine type, hours
- For movies/shows: search for where to stream, Rotten Tomatoes score, cast, director
- For books: search for author, summary, reviews, genre
- For products: search for price, reviews, features, comparisons
- For research papers: search for summary, key findings, citations, authors
- For general notes/reminders: shouldSearch = false (no search needed)
- For ambiguous single words: shouldSearch = false until clarified

Be creative - think about what would be most useful for the user to know.
If the content is just a personal note or reminder, set shouldSearch to false.`,
      },
      {
        role: "user",
        content: JSON.stringify({
          summary: perception.summary,
          detectedType: perception.contentType,
          title: perception.title,
          topics: perception.topics,
          confidence: perception.confidence,
        }),
      },
    ],
  });

  const content = response.choices[0]?.message?.content;
  if (!content) {
    return {
      shouldSearch: false,
      query: "",
      searchIntent: "",
      fieldsToExtract: [],
    };
  }

  try {
    const result = JSON.parse(content) as SearchContext;
    console.log(`[Enrichment] Search context:`, {
      shouldSearch: result.shouldSearch,
      query: result.query?.slice(0, 50),
    });
    return result;
  } catch {
    console.error("[Enrichment] Failed to parse search context");
    return {
      shouldSearch: false,
      query: "",
      searchIntent: "",
      fieldsToExtract: [],
    };
  }
}

/**
 * LLM synthesizes Tavily results into structured, useful data
 */
export async function synthesizeTavilyResults(
  tavilyData: TavilyResponse,
  searchContext: SearchContext,
  perception: PerceiveOutput,
): Promise<EnrichedData> {
  const openai = getOpenAI();

  console.log(`[Enrichment] Synthesizing ${tavilyData.results.length} results`);

  const response = await openai.chat.completions.create({
    model: "gpt-4o-mini",
    max_tokens: 1000,
    response_format: { type: "json_object" },
    messages: [
      {
        role: "system",
        content: `You are a data extraction assistant. Given web search results, extract the most useful information.

Your task:
1. Read through the search results carefully
2. Extract the specific data points that would be useful
3. Format it in a clean, structured way
4. Include source URLs for attribution

Return JSON with:
{
  "title": "Clean, accurate title/name",
  "description": "Concise but informative description (2-3 sentences)",
  "keyFacts": {
    // Dynamically structured based on what's found
    // For restaurants: address, priceRange, cuisine, rating, hours
    // For movies: streamingServices, rottenTomatoes, director, cast
    // For products: price, rating, features
    // Include whatever is most relevant and available
  },
  "tags": ["relevant", "categorization", "tags"],
  "category": "food" | "entertainment" | "reading" | "shopping" | "places" | "tech" | "research" | "other",
  "sourceUrl": "primary source URL",
  "confidence": 0.0-1.0 (how confident you are in the extracted data)
}

IMPORTANT:
- For restaurants: MUST include address (street address with city) and priceRange ($ to $$$$)
- For movies/shows: MUST include where to stream and ratings
- Extract real data from the search results, don't make things up
- If a field isn't found in the results, omit it
- Use the Tavily answer as a starting point if available`,
      },
      {
        role: "user",
        content: JSON.stringify({
          originalContent: perception.summary,
          searchIntent: searchContext.searchIntent,
          fieldsToExtract: searchContext.fieldsToExtract,
          tavilyAnswer: tavilyData.answer,
          searchResults: tavilyData.results.slice(0, 5).map((r) => ({
            title: r.title,
            content: r.content?.slice(0, 1000), // Limit content size
            url: r.url,
          })),
        }),
      },
    ],
  });

  const content = response.choices[0]?.message?.content;
  if (!content) {
    // Fallback to perception data
    return {
      title: perception.title || perception.summary?.slice(0, 50) || "Unknown",
      description: perception.summary || "",
      keyFacts: {},
      tags: perception.topics || [],
      category: mapContentTypeToCategory(perception.contentType),
      confidence: 0.3,
    };
  }

  try {
    const result = JSON.parse(content) as EnrichedData;
    console.log(`[Enrichment] Synthesized: ${result.title}`);
    return result;
  } catch {
    console.error("[Enrichment] Failed to parse synthesis result");
    return {
      title: perception.title || perception.summary?.slice(0, 50) || "Unknown",
      description: perception.summary || "",
      keyFacts: {},
      tags: perception.topics || [],
      category: mapContentTypeToCategory(perception.contentType),
      confidence: 0.3,
    };
  }
}

/**
 * LLM formats a nice response message based on enriched data
 */
export async function formatEnrichedResponse(
  enrichedData: EnrichedData,
): Promise<string> {
  const openai = getOpenAI();

  const response = await openai.chat.completions.create({
    model: "gpt-4o-mini",
    max_tokens: 300,
    messages: [
      {
        role: "system",
        content: `Format a WhatsApp confirmation message for saved content.
Keep it concise but informative. Use emojis sparingly but effectively.
Include the most useful details found.

Format:
✅ Saved: [Title]
[2-3 lines of the most relevant details with appropriate emojis]
📁 Category: [category]

EXAMPLES:
For a restaurant:
✅ Saved: Barbalu
📍 Italian restaurant in Carroll Gardens
🏠 225 Front St, Brooklyn, NY 11201
💰 $$ | ⭐ 4.5/5
📁 Category: Food

For a movie:
✅ Saved: Dune: Part Two
🎬 Sci-fi epic by Denis Villeneuve
📺 Max, Prime Video (rent)
🍅 93% RT | ⭐ 8.8 IMDb
📁 Category: Entertainment

Keep it SHORT - this is for WhatsApp.`,
      },
      {
        role: "user",
        content: JSON.stringify(enrichedData),
      },
    ],
  });

  return (
    response.choices[0]?.message?.content ||
    `✅ Saved: ${enrichedData.title}\n📁 Category: ${enrichedData.category}`
  );
}

/**
 * Main enrichment function - orchestrates the full flow
 */
export async function enrichContent(perception: PerceiveOutput): Promise<{
  enrichedData: EnrichedData;
  searchPerformed: boolean;
  searchQuery?: string;
}> {
  // Step 1: LLM decides if we should search and generates query
  const searchContext = await generateSearchQuery(perception);

  // If no search needed, return perception-based data
  if (!searchContext.shouldSearch || !isTavilyConfigured()) {
    console.log(`[Enrichment] No search needed or Tavily not configured`);
    return {
      enrichedData: {
        title:
          perception.title || perception.summary?.slice(0, 50) || "Unknown",
        description: perception.summary || "",
        keyFacts: {},
        tags: perception.topics || [],
        category: mapContentTypeToCategory(perception.contentType),
        confidence: perception.confidence || 0.5,
      },
      searchPerformed: false,
    };
  }

  // Step 2: Search with Tavily
  let tavilyResults: TavilyResponse;
  try {
    tavilyResults = await searchWithTavily({
      query: searchContext.query,
      searchDepth: "advanced",
      includeAnswer: true,
      maxResults: 5,
    });
  } catch (error) {
    console.error("[Enrichment] Tavily search failed:", error);
    return {
      enrichedData: {
        title:
          perception.title || perception.summary?.slice(0, 50) || "Unknown",
        description: perception.summary || "",
        keyFacts: {},
        tags: perception.topics || [],
        category: mapContentTypeToCategory(perception.contentType),
        confidence: perception.confidence || 0.5,
      },
      searchPerformed: false,
    };
  }

  // Step 3: LLM synthesizes results
  const enrichedData = await synthesizeTavilyResults(
    tavilyResults,
    searchContext,
    perception,
  );

  return {
    enrichedData,
    searchPerformed: true,
    searchQuery: searchContext.query,
  };
}

/**
 * Map content type to category
 */
function mapContentTypeToCategory(contentType?: string): string {
  if (!contentType) return "other";

  const categoryMap: Record<string, string> = {
    restaurant: "food",
    recipe: "food",
    movie: "entertainment",
    show: "entertainment",
    video: "entertainment",
    book: "reading",
    article: "reading",
    research: "reading",
    news: "reading",
    product: "shopping",
    place: "places",
    reminder: "tasks",
    note: "notes",
  };

  return categoryMap[contentType.toLowerCase()] || "other";
}
